# Generated by Django 5.1.1 on 2024-10-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "healmind",
            "0002_question_questionnaire_choice_question_questionnaire_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="text",
            new_name="response_text",
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="score",
            new_name="response_value",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="question_content",
        ),
        migrations.RenameField(
            model_name="questionnaire",
            old_name="title",
            new_name="questionnaire_name",
        ),
        migrations.RenameField(
            model_name="result",
            old_name="result_text",
            new_name="result_description",
        ),
        migrations.RenameField(
            model_name="result",
            old_name="score_max",
            new_name="score_high",
        ),
        migrations.RenameField(
            model_name="result",
            old_name="score_min",
            new_name="score_low",
        ),
        migrations.RemoveField(
            model_name="question",
            name="score_weight",
        ),
        migrations.AddField(
            model_name="result",
            name="stress_level",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="result",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="healmind.questionnaire",
            ),
        ),
    ]
